### PR TITLE
Add data to post request

### PR DESCRIPTION
**Pull request by Kat-CeDe**

### CODE REVIEW

**Review by kennymc-c — CHANGES_REQUESTED** [review]
See my comments on Discord: Please do not use ? as a separator as it is a reserved url character (https://documentation.mapp.com/1.0/en/url-encoding-and-what-characters-are-valid-in-a-uri-36147771.html). Also you do not need line 116 if data is already defined as a dictionary.

**Review by kennymc-c — CHANGES_REQUESTED** [review]
Please do not change the default timeout. You could add a function to change the default timeout with an environment variable if this has been set

**Review by kennymc-c — APPROVED** [review]

**Review by kennymc-c — CHANGES_REQUESTED** [review]
The separator should be a paragraph (§) not a dollar sign ($). A dollar sign is also a reserved character. 
Can you also remove line 116 and adjust the example code to use dictionaries as data payload? The conversion is not really needed here since you can just use python dictionaries after the separator that are required by requests.
Please also add a check to let this still work without data payload:
```
if "§" in cmd_param:
                    url, data = cmd_param.split("§")
                    r = rq_post(url, data, timeout=rqtimeout)
else:
                    r = rq_post(cmd_param, timeout=rqtimeout)
```

**Review by kennymc-c — CHANGES_REQUESTED** [review]
The proposed syntax with `=` and `,` for adding data is too similar to url query string which are a different thing and this can easily be mixed up. Users should be able to directly use dictionaries in the form of  `{'key1': 'value1', 'key2': 'value2'}`.
But I understand that your syntax is easier to write. Maybe you could add a check that both syntaxes will work? A pipe `|` as a separator is maybe even easier to read?

**Comment by Kat-CeDe** [comment]
What about | as a separator for your idea data without any conversion instead of trying to analyze the parameter. This way anything can be send. I tried to test | {'key1': 'value1', 'key2': 'value2'} but on my system  I cannot see anything. My system needs a dictionary that´s why I used the conversion.

**Comment by kennymc-c** [comment]
By separator I meant the one between multiple key/value pairs instead of a comma.
But let's just keep your previous version with url:port§key1=value1,key2=value2 for now. Maybe I add the possibility to also use dictionaries later.

Regarding the timeout: I will try to make this configurable during the setup flow

**Comment by Kat-CeDe** [comment]
Hi kenny,
I somehow liked your idea to add data without any conversion that´s why I did it this way. With § and | as separator it is even more flexible. Do you have use cases for get, put and patch? I saw that these are use by the R2 API but I found no use case on the remote itself.

Ralf

**Review by kennymc-c — APPROVED** [review]

**Comment by kennymc-c** [comment]
I will add the same logic to all other methods as well

**Pull request merged**
